export const ADD_TODO = "ADD_ITEM";
export const REMOVE_TODO = "REMOVE_ITEM";
export const TOGGLE_COMPLETE = "TOGGLE_COMPLETE";
export const FETCH_TODOS_REQUEST = "FETCH_ITEMS_REQUEST";
export const FETCH_TODOS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_TODOS_FAILED = "FETCH_ITEMS_FAILED";
